version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./sql-init/:/docker-entrypoint-initdb.d/
volumes:
  postgres-db:
